### ISSUE TITLE
README suggestions

### ISSUE THREAD

**Issue by wavebeem** [quack/quack#10]
### Just a few suggestions for how some paragraphs could be reworded

> More than a programming language, Quack is also a concept. The objective is to implement a type-safe and productive programming language, multi-paradigm, that allows you to write consistent and legible code once and run in different targets.

Quack is a type-safe, multi-paradigm programming language. Quack enables you to write consistent and legible code, and run it on different platforms.

> Quack supports different programming paradigms, mainly functional and imperative one

Quack supports many programming paradigms, especially functional and imperative programming.

> You can create operators **_in**_ compile time

You can create operators **_at**_ compile time

> Please, note that Quack is in it early stage, and in constant development

Please note that Quack is in its early stage, and in constant development

> Don't you know how you can help? Well, 

There are many ways to help!

> Doubts? contact me on marcelocamargo@linuxmail.org. It will be a pleasure to answer!

Questions or concerns? Contact me at marcelocamargo@linuxmail.org and I'll be happy to answer.

**Comment by sergiors** [comment]
@wavebeem could open a PR with that?

**Comment by wavebeem** [comment]
If you want all of those changes, sure! I figured I'd put it in an issue in case we wanted discussion on it.

**Comment by joaolucasl** [comment]
Just wondering, why was this reverted @sergiors ? 

EDIT: Nvm, didn't see the edits live on `master`

**Comment by haskellcamargo** [comment]
@joaolucasl, he reverted accidentally. It was already re-reverted, :dancers:
