### ISSUE TITLE
Bug on conditionals for IfStmt (and probably the others as well)

### ISSUE THREAD

**Issue by luizperes** [quack/quack#100]
the code below is parsing the `ReturnStmt` as an expression:

```
fn fib(n)
  if n = 0 or n = 1 ^ n
...
```
It is returning the condition as `n = 0 or n = 1 ^ n` and the `body` list of stmts empty.

**Comment by haskellcamargo** [comment]
This happens because `^` is used also as an infix expression. However, it has the same behavior as `xor` operator, therefore we can kill `<expr> ^ <expr>`, removing the ambiguity.

##### TODO: Remove `^` operator

**Comment by luizperes** [comment]
we will replace it with `xor`, correct?

**Comment by luizperes** [comment]
I have checked and I saw that `xor` has been already in use by the __logical__ `xor`. I do not think that we should remove this operator, can we refine it? Any thoughts @sergiors @iagocaldeira @joaolucasl @ythecombinator ?

**Comment by joaolucasl** [comment]
I reckon we could use `<!>` instead? It's pretty ugly, but ¯\_(ツ)_/¯

**Comment by luizperes** [comment]
I actually don't think that it is a bad idea :D, however i have got to check if it isn't ambiguous

**Comment by haskellcamargo** [comment]
`xor` is polymorphic. Solved.
