### ISSUE TITLE
Documentation

### ISSUE THREAD

**Issue by ShalokShalom** [quack/quack#111]
Is there anywhere a documentation, explaining the syntax and all that?

**Comment by luizperes** [comment]
Hi @ShalokShalom, we do not have any documentation for `Quack` as it is not done yet (meaning that it is not (com|trans)piling) and our grammar has had a lot of changes making this process not very feasible. For now, I believe that you can check our [test suit](https://github.com/quack/quack/tree/master/tests/stmt). There are some examples there and I believe that they can help you to get started. Other than that, I will invite you to our [slack](https://quack-lang.slack.com). From there, you can get closer to our latest updates!

We are planning to release `Quack` by __end__ of 2017 and there are still many things to be improved, such tasks for the lexer, parser, type checker, scope, documentation and others, so, feel free to help us with PRs! :)
Our TODO lists are:
 - https://github.com/quack/quack/blob/master/TODO.md
 - https://github.com/quack/quack/blob/master/TYPECHECKER_TODO.md

**Comment by ShalokShalom** [comment]
Thanks a lot. I am a beginner, so i was searching more for something like a tutorial course. 

Good luck 👍
