### ISSUE TITLE
Replace all sizeof by count

### ISSUE THREAD

**Issue by haskellcamargo** [quack/quack#128]
According to `hh_client`, `sizeof` has been deprecated and may be confusing because it is used, in C, to count the size in bytes of the types (instead of the length). We shall look for all `sizeof` in all PHP files and use `count` instead.

This is a beginner friendly issue and pull-requests are welcome!
If you are interested in getting this tasks, comment here.

**Comment by Soben** [comment]
I'll grab this and take care of it tomorrow.

**Comment by Soben** [comment]
... or even now :)

**Comment by Soben** [comment]
https://github.com/quack/quack/pull/129 is pending moderation and script verification. Interesting plugin, and looking forward to trying it out.

**Comment by haskellcamargo** [comment]
Closed by #129

**Comment by rafaelcn** [comment]
I came here too late ☹️

**Comment by haskellcamargo** [comment]
@rafaelcn there is still #130
