### ISSUE TITLE
Replace Logo

### ISSUE THREAD

**Issue by haskellcamargo** [quack/quack#5]
Replace current logo (Urano) by the next one (Quack). 
- [x] Uncomment `README.md`
- [x] Upload file to `/resource`

**Comment by ythecombinator** [comment]
Hey @haskellcamargo here is my logo proposal:

**The Duck**

For the duck I thought of a flat draw with a flat color scheme. The main color is called _Ripe Lemon_ (`#f7ca18`) and comes from [this yellow palette](http://www.flatuicolorpicker.com/yellow). Its wing is painted in the next color from a monochromatic scheme based on _Ripe Lemon_: `#edbf08` as you can check [here](http://www.colorhexa.com/f7ca18). Its beak is colored is in two shades of orange (`#e67e22` and `#d35400`) which come from [this palette](http://flatuicolors.com/). It also has well-defined stroke paints in the same color user in the eye (`#2c3e50`) and whose 
widths vary from `0,5` to `2.0` pixels.

> There is also a **very opinionated** easter egg in its wing which reminds me the creator of the lang - and which can be eventually removed.

![Duck](http://i.imgur.com/WaAwRaV.png)

**The Name**

I chose a flat _sans-serif typeface_ font called _Quicksand_, which you can check [here](http://www.fontsquirrel.com/fonts/quicksand). Also I preferred to keep the _phonetic transcription_ to focus on the character of _onomatopoeia_ from the lang name.

![Name](http://i.imgur.com/dIqlLwq.png)

**The Slogan**

The slogan uses the very same font from the name. It's a contraction of the original description from the repo:

>  A multi-paradigm programming language with gradual and duck typing that targets PHP and JS.

Becomes:

> A multi-paradigm lang with gradual and duck typing.

Also, the color used is the same from the duck's eyes and stoke paint (`#2c3e50`).

![Slogan](http://i.imgur.com/trGjMux.png)

**Grabbin' All Together**

The logo goes like this:

![Logo](http://i.imgur.com/L1mn7va.png)

And a _squared logo_ - for the organization on Github - goes like:

![Logo Org](http://i.imgur.com/LRsgAFD.png)

Hope you like it :smile_cat:

**Comment by ythecombinator** [comment]
I implemented the changes I mentioned above from my commits ce2b1bb to 0800aad :)
