### ISSUE TITLE
Alternative for class-based programming

### ISSUE THREAD

**Issue by sergiors** [quack/quack#51]
Hi, I think Rust way is good; better than class-based programming.

Ex:

``` rust
struct User {
    name: String
}

impl User {
    fn new(name: &str) -> User {
        User {
            name: name.to_string()
        }
    }

    fn get_name(self) -> String {
        self.name
    }
}

fn main() {
    let s = User::new("Sérgio");
    println!("Hello {}", s.get_name());
}
```

What do you think?

CC: @haskellcamargo @luizperes @joaolucasl 
References #45

**Comment by luizperes** [comment]
Hi @sergiors, could you explain better your thoughts of why Rusty's way is better than class-based programming?

**Comment by sergiors** [comment]
@luizperes class-based programming is just a sugar syntax.

Struct is a representation for data.

Let's think If `php` has property type.

``` php
// almost a struct
class User {
 public int $id;
 public string $name;
}
function get_name(User $user) {
    return $user->name;
}
function change_name(User $user, $new_name) {
    $new = new User;
    $new->id = $user->id;
    $new->name = $new_name;
    return $new;
}
```

With `impl` it's possible to create operations for `struct` (don't need pass object, `self` is the `struct`), this way is easer to organize without creating objects.

**Comment by luizperes** [comment]
@sergiors it is sugar syntax indeed, but in spite of being pretty similiar, there are few differences between them in popular languages:
-  `structs` as far as I understand don't have `inheritance` directly (depending on the implementation).
- the use of `self` is also sugar syntax for both `structs` and `classes`.
- Imagine **Swift**, I love the idea of having structs for small objects (passed by value) and classes for big objects (passed by reference).
- In **C++**, you cannot define `templates` for `structs`.

Other than that, `classes` and `structs` are the same thing.

I don't know why, but in general (depending on the language of course), I prefer to keep my `structs` on the stack and and objects on the `heap`. In this way I see `struct` as an extension for primitive types, as a heterogeneous segment of memory on the `stack`, while `classes` are the same thing on the heap, but with the full support to OO.

Therefore, my vote is to keep both of them. In this way we would have the possibility to create projects by using either structs, classes or both. :) That needs to be discussed better.

**Comment by joaolucasl** [comment]
I think just like Javascript, we can benefit from both approaches. 
I don't know if that's a possibility due to Quack targeting compilation to other languages but I'm one with those who think the best option is a mixed approach like JS's (and I must say I like prototypal inheritance better than classical class-based OOP)

This is gonna be a good discussion, though. Keen to see other people's point-of-view.

**Comment by haskellcamargo** [comment]
See #59
