### ISSUE TITLE
Parentheses vs brackets for functions

### ISSUE THREAD

**Issue by haskellcamargo** [quack/quack#72]

**Comment by haskellcamargo** [comment]
![ata](http://ues.li/ata.jpg)

**Comment by sergiors** [comment]
Parentheses!

**Comment by johnidm** [comment]
Brackets,  for me parentheses is confused.

**Comment by davidbranco** [comment]
Parentheses!

**Comment by sergiors** [comment]
Can be just comfortable for me, but I see brackets as a way to access a index in array.

`foo()` a think, is a function
`foo[...10]` is a array

**Comment by johnidm** [comment]
@sergiors you are right.

**Comment by johnidm** [comment]
@sergiors you are right, thanks for explanation.

**Comment by luizperes** [comment]
This one was already decided, no @joaolucasl @haskellcamargo?

**Comment by luizperes** [comment]
@haskellcamargo can you follow up the latest syntax for functions? Thanks!

**Comment by haskellcamargo** [comment]
Parenthesis are being used. Brackets are for anonymous functions.

```js
fn add(a, b)
    ^ a + b
end
```

```js
const add :- &[a, b] -> a + b
```
