### ISSUE TITLE
SwitchStmt with multiple `else` cases

### ISSUE THREAD

**Issue by luizperes** [quack/quack#77]
The `SwitchStmt` is allowing multiple `else` cases. Is that behavior valid?

[Grammar.php#L425](https://github.com/quack/quack/blob/master/src/parser/Grammar.php#L425)

**Comment by haskellcamargo** [comment]
It is valid in the grammar, taking account the order of these checks is invariant. However, I'll fix this (at least for now) in the type-checker. We'll need after to make a more generic class for semantic errors.

**Comment by haskellcamargo** [comment]
Also, a detail is that checking type only based on `->code` is error-prone. It is valid for literal types, but aren't precise enough when dealing with subtyping. For example, `Map.of(string)` to `Map.of(int)`. I've written a specialized function for that (called `->isExactlySameAs(Type $other)`), that will, with invariance, deep check the type. Therefore:

``` diff
- if ($case_type->code !== $value_type->code)
+ !$case_type->isExactlySameAs($value_type)
```

The function definition may be found [here](https://github.com/quack/quack/blob/master/src/types/Type.php#L142).
