### ISSUE TITLE
Expressions do not have a common field for string representation of value

### ISSUE THREAD

**Issue by luizperes** [quack/quack#79]
Case-statements for example, use print the property `$case->value->value` when the expression's type is not compliant with the switch-statement's type. It makes sense once it is a value inside a value.
Although, that does not work for all expressions. The parser accepts case-statements such as:

``` Swift
let y :- "blah"
let x :- 1
switch x
    case 0 /* stmt */
    case y /* stmt */
end
```

In the case above, `y` has the type of `NameExpr` and the `value` field is not present for that type. It is called `name` instead.
My question is: shouldn't we have a `toString`-like method on `Quack` for `Statements` and `Expressions`?

**Comment by haskellcamargo** [comment]
When the expression type is not compliant, we'll have base on the index of the `case`, at least for now. We still don't track source information on type-checking. We can get the type of any expression with `->getType()`. The `Type` class is overloaded for `(string)` conversion, rendering a human readable type.

**Comment by luizperes** [comment]
mmmm.... got it! I think that I can solve that for now!

**Comment by luizperes** [comment]
Did I solve this? (completely forgot)

**Comment by luizperes** [comment]
@haskellcamargo what is the status of this issue? I believe you solved that on https://github.com/quack/quack/pull/106, right?
