### ISSUE TITLE
Labels are being parsed wrong

### ISSUE THREAD

**Issue by luizperes** [quack/quack#91]
Labels are not being recognized by Quack when I try to do:

```
:- firstLabel
for i from 1 to 10 by 2
  :- secondLabel
  for j from 1 to 10
    {- blah -}
  end
end
```

The `ForStmt`s property `by` is being parsed as it follows:
![by_ast](https://user-images.githubusercontent.com/6173065/27707555-90ff53e8-5cca-11e7-925c-a218d38ee399.png)

Discussing this matter with @haskellcamargo, it seems that we have an ambiguity for our labels.

**Comment by haskellcamargo** [comment]
Closed by #92
